using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using NJsonSchema;
using NJsonSchema.CodeGeneration.CSharp;

var root = Directory.GetParent(AppContext.BaseDirectory)!.Parent!.Parent!.Parent!.Parent!.Parent!.FullName;
var schemaRoot = Path.Combine(root, "tests", "contracts", "schemas", "v1");
var output = args.Length == 2 && args[0] == "--output" ? args[1] : throw new ArgumentException("Use --output <path>.");
var envelopeNode = JsonNode.Parse(await File.ReadAllTextAsync(Path.Combine(schemaRoot, "event-envelope.schema.json")))!;
var envelopeDefinitions = envelopeNode["$defs"]!.DeepClone();
var eventFiles = new[] { "bid-accepted.schema.json", "auction-purchased.schema.json", "auction-closed.schema.json", "winner-selected.schema.json", "auction-cancelled.schema.json" };
var settings = new CSharpGeneratorSettings
{
    Namespace = "AuctionOperationsPortal.Contracts.Generated",
    ClassStyle = CSharpClassStyle.Record,
    JsonLibrary = CSharpJsonLibrary.SystemTextJson,
    GenerateNullableReferenceTypes = true,
    GenerateNativeRecords = true,
    NumberType = "decimal",
    DateTimeType = "DateTimeOffset"
};
var generated = new List<string>();
var typeNames = new Dictionary<string, string>(StringComparer.Ordinal)
{
    ["bid-accepted.schema.json"] = "GeneratedBidAcceptedPayload",
    ["auction-purchased.schema.json"] = "GeneratedAuctionPurchasedPayload",
    ["auction-closed.schema.json"] = "GeneratedAuctionClosedPayload",
    ["winner-selected.schema.json"] = "GeneratedWinnerSelectedPayload",
    ["auction-cancelled.schema.json"] = "GeneratedAuctionCancelledPayload"
};
foreach (var file in eventFiles.OrderBy(file => file, StringComparer.Ordinal))
{
    var eventNode = JsonNode.Parse(await File.ReadAllTextAsync(Path.Combine(schemaRoot, file)))!.AsObject();
    eventNode["$defs"] = envelopeDefinitions!.DeepClone();
    RewriteReferences(eventNode);
    var resolvedNode = ResolveReferences(eventNode, eventNode["$defs"]!.AsObject()).AsObject();
    resolvedNode.Remove("$defs");
    var payloadSchema = resolvedNode["allOf"]![1]!["properties"]!["payload"]!.DeepClone()!.AsObject();
    payloadSchema["$schema"] = "https://json-schema.org/draft/2020-12/schema";
    payloadSchema["$id"] = $"urn:dbap:operations:codegen:{Path.GetFileNameWithoutExtension(file)}";
    payloadSchema["title"] = $"Generated{Path.GetFileNameWithoutExtension(file).Replace("-", string.Empty, StringComparison.Ordinal)}Payload";
    var schema = await JsonSchema.FromJsonAsync(payloadSchema.ToJsonString());
    var generator = new CSharpGenerator(schema, settings);
    generated.Add(generator.GenerateFile(schema, typeNames[file]));
}

var header = "// <auto-generated />\n// Generated from dbap-integration-contracts v1.0.0, commit 6c89fb85d96110b881ff789470e3d7acfd5331e1.\n// Generator: NJsonSchema.CodeGeneration.CSharp 11.3.2.\n// Do not edit manually.\n\n";
Directory.CreateDirectory(Path.GetDirectoryName(output)!);
var outputText = header + string.Join("\n", generated)
    .Replace("#pragma warning disable // Disable all warnings", "#pragma warning disable SA1600, SA1633", StringComparison.Ordinal)
    .Replace("11.3.2.0.0", "11.3.2.0", StringComparison.Ordinal);
outputText = Regex.Replace(outputText, "//----------------------\\n// <auto-generated>.*?//----------------------\\n", string.Empty, RegexOptions.Singleline | RegexOptions.CultureInvariant);
outputText = Regex.Replace(outputText, "11\\.3\\.2\\.0 \\([^)]*\\)", "11.3.2.0", RegexOptions.CultureInvariant);
await File.WriteAllTextAsync(output, outputText);

static void RewriteReferences(JsonNode node)
{
    if (node is JsonObject objectNode)
    {
        if (objectNode["$ref"] is JsonValue reference && reference.TryGetValue<string>(out var value) && value.StartsWith("urn:dbap:event:event-envelope:v1#", StringComparison.Ordinal))
        {
            objectNode["$ref"] = value["urn:dbap:event:event-envelope:v1".Length..];
        }

        foreach (var child in objectNode.Select(pair => pair.Value))
        {
            if (child is not null) RewriteReferences(child);
        }
    }
    else if (node is JsonArray arrayNode)
    {
        foreach (var child in arrayNode)
        {
            if (child is not null) RewriteReferences(child);
        }
    }
}

static JsonNode ResolveReferences(JsonNode node, JsonObject definitions)
{
    if (node is JsonObject objectNode)
    {
        if (objectNode["$ref"] is JsonValue reference && reference.TryGetValue<string>(out var value) && value.StartsWith("#/$defs/", StringComparison.Ordinal))
        {
            var name = value["#/$defs/".Length..];
            if (definitions[name] is null) throw new InvalidOperationException($"Unresolved local schema reference: {value}");
            return ResolveReferences(definitions[name]!.DeepClone()!, definitions);
        }

        foreach (var property in objectNode.ToArray())
        {
            if (property.Value is not null) objectNode[property.Key] = ResolveReferences(property.Value.DeepClone()!, definitions);
        }
    }
    else if (node is JsonArray arrayNode)
    {
        for (var index = 0; index < arrayNode.Count; index++)
        {
            if (arrayNode[index] is not null) arrayNode[index] = ResolveReferences(arrayNode[index]!.DeepClone()!, definitions);
        }
    }

    return node;
}
